release: v1.0.0a1
inveniosoftware/invenio-sequencegenerator pull request #16
Opened 2016-12-15 12:30 UTC by omelkonian

Signed-off-by: Orestis Melkonian <melkon.or@gmail.com>

2016-12-15 13:54 UTC, jirikuncar commented on CHANGES.rst
> +Version 1.0.0 (released December 15, 2016)
1.0.0a1

2016-12-15 13:54 UTC, jirikuncar commented on RELEASE-NOTES.rst
> +   $ pip install invenio-sequencegenerator==1.0.0
1.0.0a1

2016-12-15 13:54 UTC, jirikuncar commented on invenio_sequencegenerator/version.py
> +__version__ = "1.0.0.a1"
1.0.0a1

2017-01-12 12:43 UTC, egabancho commented
LGTM

2017-01-12 12:45 UTC, egabancho approved these changes

2017-01-12 15:28 UTC, jirikuncar requested changes

2017-01-12 15:28 UTC, jirikuncar commented on RELEASE-NOTES.rst
> +   http://invenio-sequencegenerator.readthedocs.io/en/v1.0.0
`1.0.0a1`

2017-01-12 15:28 UTC, jirikuncar commented on CHANGES.rst
> +Version 1.0.0a1 (released December 15, 2016)
needs an update

2017-01-12 15:28 UTC, jirikuncar commented on RELEASE-NOTES.rst
> +   $ pip install invenio-sequencegenerator==1.0.0a1
There are more versions and dates that should be updated (see the top of the file).

2017-01-16 09:37 UTC, omelkonian commented
@jirikuncar Should I update the release data again?

2017-01-17 14:50 UTC, jirikuncar requested changes
Please add 2017 to copyright headers in touched files.

2017-01-17 15:47 UTC, omelkonian commented
@jirikuncar done!

2017-01-17 16:28 UTC, jirikuncar approved these changes

2017-01-17 16:33 UTC, merged