cli: basic interface
inveniosoftware/invenio-sequencegenerator pull request #19
Opened 2017-01-23 10:59 UTC by omelkonian

* Adds basic CLI, including creating new sequences and
   asking for next counters on existing sequences.

 * Adds tests for coverage.

Signed-off-by: Orestis Melkonian <melkon.or@gmail.com>

2017-01-26 08:19 UTC, egabancho requested changes
@omelkonian What do you think about updating the docs with a CLI usage section?

2017-01-26 08:19 UTC, egabancho commented on tests/test_cli.py
> +
I guess we don't need all this blanks 😉

2017-01-26 08:36 UTC, jirikuncar commented on invenio_sequencegenerator/ext.py
> +        app.cli.add_command(sequences)
You can use `flask.commands` entry point.

2017-01-26 12:12 UTC, egabancho approved these changes

2017-01-30 09:51 UTC, jirikuncar commented on tests/test_cli.py
> +    #
Playlists and authors should be separate test cases.

2017-02-06 18:29 UTC, merged